name: JS Tests

on:
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop" ]

jobs:
  tests:
    name: ${{ matrix.os }} / Node.js 18
    runs-on: ${{ matrix.image }}
    env:
      MONGODB_LINK: mongodb://localhost:27017/test
    strategy:
      matrix:
        image: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start MongoDB container
        run: |
          docker run -d -p 27017:27017 --name mongodb mongo:5.0

      - name: Backend - Install dependencies
        working-directory: backend
        run: npm ci

      - name: Backend - Run tests
        working-directory: backend
        run: npm test

      - name: Stop MongoDB container
        if: always()
        run: docker stop mongodb && docker rm mongodb